### ISSUE TITLE
Terminal ligatures doesnt work on Vscode 1.76.0 

### ISSUE THREAD

**Issue by ufukbakan** [SeyyedKhandon/firacode-vscode-extension#1]
Installed firacode fonts and extension on windows 10 but I don't see a spinning circle instead of \ / characters:

terminal with monospace font:
![image](https://user-images.githubusercontent.com/44516872/222736782-683be125-3001-4f17-87d3-70b56ed7e264.png)

terminal with fira code font:
![image](https://user-images.githubusercontent.com/44516872/222737947-fbc4adea-6a7c-484d-ad8d-7e84bcc6d0da.png)

my config:
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "editor.fontSize": 14,
    "editor.fontWeight": "normal",
    "editor.fontVariations": true,
    "terminal.integrated.fontFamily": "Fira Code",
    "terminal.integrated.fontSize": 14,
    "terminal.integrated.fontWeight": "normal",
    "terminal.integrated.fontWeightBold": "bold",

about vscode:
Version: 1.76.0 (user setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by SeyyedKhandon** [comment]
The feature is still an open issue for vscode's terminal:
https://github.com/microsoft/vscode/issues/34103 

But if you want to make it work, you can use nerd fonts and star ship:
https://code.visualstudio.com/docs/terminal/appearance
https://starship.rs/
