### ISSUE TITLE
Font not working in Codespaces

### ISSUE THREAD

**Issue by Jay-Karia** [SeyyedKhandon/firacode-vscode-extension#4]
I am using GitHub codespaces and have installed the extension, along with local font files on my PC, still unable see fira code fonts.

Extension

![ext](https://github.com/user-attachments/assets/2030fb1f-775b-472a-9332-87563735d8f6)

Settings

![settings](https://github.com/user-attachments/assets/8afff817-ecc2-4d29-8860-8321319a28ec)

Code

![code](https://github.com/user-attachments/assets/33d9d4cb-6b0b-4d22-ba3c-5732e85147bb)

Local files

![local](https://github.com/user-attachments/assets/44341f98-0b55-4f9a-9a14-e5a80f518547)

**Comment by SeyyedKhandon** [comment]
Have you done this part? (the installation part)
<img width="688" alt="image" src="https://github.com/user-attachments/assets/0929cc4d-fb6b-44a3-9a38-24bc9dc6619b">

Normally you should be able to install them by double click (in windows or mac), if you are in linux, you may need to create a `.fonts` folder in your home directory and move those files into there...

Let me know the result

**Comment by Jay-Karia** [comment]
Yeah , already installed the font.

**Comment by Jay-Karia** [comment]
Fonts are now working,

**Tried re-initializing codespace**
